# Generated by Django 4.1.3 on 2022-11-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('accept', models.BooleanField()),
            ],
        ),
    ]
