# Generated by Django 4.1.1 on 2022-11-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginService", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="email",),
        migrations.AddField(
            model_name="account",
            name="user_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
