# Generated by Django 4.1.1 on 2022-11-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginService", "0003_account_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
