# Generated by Django 4.1.1 on 2022-11-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginService", "0004_account_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="work_status",
            field=models.CharField(default="", max_length=50),
        ),
    ]
