# Generated by Django 4.1.1 on 2022-11-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginService", "0005_account_work_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="token",
            field=models.CharField(default="", max_length=200),
        ),
    ]
