# Generated by Django 4.1.1 on 2022-11-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginService", "0006_account_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="work_time",
            field=models.IntegerField(default=0),
        ),
    ]
